### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by allyaminou** [userMacieG/engine#1]
The scripts is acting weird..i deleted all other scripts that this one have intergrated, but when i turn the engine on i can only reverse and can't go foward , if i restart the script works fine. Do you know what could be the issue ?

**Comment by userMacieG** [comment]
When you spawn car, you need to trigger client event: `TriggerEvent("engine:client:state", vehicle, state)`
or set in config option `Config.DisableStartAfter.PressingW` to false.
This option is workaround for starting engine by pressing W key.
